In [52]:
!pip install numpy

In [53]:
!pip install torch

In [54]:
!pip install torchvision

In [55]:
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [56]:
t=np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [57]:
print('Rank of t: ',t.ndim)
print('Shape of t: ',t.shape)

Rank of t:  1
Shape of t:  (7,)


In [58]:
print('t[0] t[1] t[-1] = ',t[0],t[1],t[-1])
print('t[2:5] t[4:-1] = ',t[2:5],t[4:-1])
print('t[:2] t[3:] = ',t[:2],t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [59]:
t=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [60]:
print('Rank of t: ',t.ndim)
print('Shape of t: ',t.shape)

Rank of t:  2
Shape of t:  (4, 3)


In [61]:
#1D Array with PyTorch
t=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [62]:
#2D Array with PyTorch
t=torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1])
print(t[:1])
print(t[1:])
print(t[0:2,1:3])
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([1., 2., 3.]) tensor([4., 5., 6.])
tensor([[1., 2., 3.]])
tensor([[ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[2., 3.],
        [5., 6.]])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [63]:
#Broadcasting
#Same shape
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [64]:
#Vector + scalar
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.]])


In [65]:
#2x1 Vector + 1x2 Vector
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3],[4]])
print(m1)
print(m2)
print(m1+m2)

tensor([[1., 2.]])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]])


In [66]:
print()
print("-------------")
print("Mul vs Matmul")
print("-------------")
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
print("Shape of Matrix 1: ",m1.shape)
print("Shape of Matrix 2: ",m2.shape)
print(m1)
print(m2)
print(m1.matmul(m2))

m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
print("Shape of Matrix 1: ",m1.shape)
print("Shape of Matrix 2: ",m2.shape)
print(m1)
print(m2)
print(m1*m2)
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [67]:
#Mean
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [68]:
#Can't use mean() on integers
t=torch.LongTensor([1,2])
try:
  print(t.mean())
except Exception as exc:
  print(exc)

mean(): input dtype should be either floating point or complex dtypes. Got Long instead.


In [69]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [70]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [71]:
#Sum
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [72]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [73]:
#Max and Argmax
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [74]:
print(t.max())

tensor(4.)


In [75]:
print(t.max(dim=0)) #returns two values: max and argmax
print("Max: ",t.max(dim=0)[0])
print("Argmax: ",t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [76]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [77]:
#View(Reshape)
#view(-1), reshape(-1) : Tensor 자료형 차원 풀기
#view(n, -1), reshape(n, -1) : Tensor 자료형 차원 풀되, [n x ] 형태로 1차원 유지하기
t=np.array( [[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]] )
ft=torch.FloatTensor(t)
print(ft.shape)
print(ft)

torch.Size([2, 2, 3])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [78]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [79]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [80]:
#squeeze함수는 차원이 1인 차원을 제거해준다.
#따로 차원을 설정하지 않으면 1인 차원을 모두 제거한다. 
#그리고 차원을 설정해주면 그 차원만 제거한다.
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [81]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [82]:
#unsqueeze함수는 squeeze함수의 반대로 1인 차원을 생성하는 함수이다. 
#그래서 어느 차원에 1인 차원을 생성할 지 꼭 지정해주어야한다.
ft=torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [83]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [84]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [85]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [86]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [87]:
#Type Casting
lt=torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [88]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [89]:
bt=torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [90]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [91]:
#Concatenate
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])
print(x)
print(y)
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [92]:
#Stacking
#stack함수는 지정하는 차원으로 확장하여 tensor를 쌓아주는 함수
#(지정하는 차원에 새로운 차원이 생긴다=차원의 수가 증가한다)
#tensor를 쌓아주는 함수이기 때문에 두 tensor의 차원이 정확히 일치해야 쌓을 수 있다
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [93]:
#Ones and Zeros
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [94]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [95]:
#In-place Operation
x=torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [96]:
training_data=datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

In [97]:
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

In [99]:
batch_size = 64

#create data loaders.
train_dataloader = DataLoader(training_data,batch_size=batch_size)
test_dataloader=DataLoader(test_data,batch_size=batch_size)

for X,y in test_dataloader:
  print(f"Shape of X:[N,C,H,W:]: {X.shape}")
  print(f"Shape of y:{y.shape}{y.dtype}")
  print(y)
  break

Shape of X:[N,C,H,W:]: torch.Size([64, 1, 28, 28])
Shape of y:torch.Size([64])torch.int64
tensor([9, 2, 1, 1, 6, 1, 4, 6, 5, 7, 4, 5, 7, 3, 4, 1, 2, 4, 8, 0, 2, 5, 7, 9,
        1, 4, 6, 0, 9, 3, 8, 8, 3, 3, 8, 0, 7, 5, 7, 9, 6, 1, 3, 7, 6, 7, 2, 1,
        2, 2, 4, 4, 5, 8, 2, 2, 8, 4, 8, 0, 7, 7, 8, 5])
